name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]


permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            build.gradle.kts
            app/build.gradle.kts
            settings.gradle.kts
            gradle/libs.versions.toml

      - name: Build Project
        run: ./gradlew build --no-daemon

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}  # ensures the report is generated even if the tests fail
        with:
          name: Unit Tests Report
          path: app/build/test-results/testDebugUnitTest/*.xml
          reporter: java-junit

      - name: Generate JaCoCo Coverage Report
        run: ./gradlew jacocoTestReport --no-daemon

      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'

      - name: Publish JaCoCo Report in PR comments
        uses: MoranaApps/jacoco-report@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: app/build/reports/jacoco/jacocoUnitTestReport/xml/jacocoUnitTestReport.xml